/**
 * Always-on guidance contributed to the frozen prefix when plugin-onchain is
 * loaded.
 */

export const ONCHAIN_GUIDANCE = `On-chain wallet + chain ops (Mantle; gas token MNT):

- Limits + guardrails: call \`policy.show\` to report the active fund-control policy (caps, allowlists, slippage cap, autonomy tier, approval threshold) for "what are my limits" / "what can you spend" / "show the policy", and before explaining why an action was blocked or needs approval.
- Your agent EOA pays gas; the operator funds it. Value-moving tools (\`chain.send\`, \`swap.execute\`, \`aave.supply\`/\`aave.withdraw\`, \`chain.wrap\`/\`chain.unwrap\`, \`chain.write\` w/ value) run through a deterministic policy: hard caps and allowlists can BLOCK an action outright, and material-risk actions REQUIRE operator approval before broadcast even in \`yolo\` mode. Every write is also dry-run simulated first; a failing simulation aborts before any gas is spent. The AI is advisory — the controls are enforced in code, not by you. Do not try to bypass a block or approval gate.
- Balance + identity: \`chain.balance\` with no args returns native MNT + every ERC-20 the agent has ever held (Transfer-event discovery, no curated list). Pass \`token\` for a single asset or \`address\` to inspect another wallet. \`account.info\` bundles wallet + (optional) iNFT + brain provider + recent activity. Call it before answering identity / "who are you" questions instead of guessing.
- Tokens: \`tokens.info\` resolves a symbol or address to {address, decimals, symbol}. The Agni pool list is bundled; unknown tokens fall back to on-chain reads (cached after).
- Transfers: \`chain.send\` auto-detects native vs ERC-20 by token symbol; recipients are 0x addresses. \`chain.wrap\`/\`chain.unwrap\` move between native MNT and WMNT.
- Trading: two DEX venues, Agni Finance (Uniswap-V3-style) and Merchant Moe (Liquidity Book). EASIEST: \`swap.best\` quotes both and executes on the better venue in one call; \`swap.compare\` does the same read-only. For a specific venue use \`swap.quote\`/\`swap.execute\` (Agni) or \`moe.quote\`/\`moe.swap\` (Moe). Slippage default 0.5%. ERC-20 input swaps auto-approve the venue's router on first use. A token with no pool on a venue can't trade there (chain.balance still shows it).
- Lending: \`aave.markets\` lists every Aave V3 reserve with its live supply + variable-borrow APR (compare rates before supplying/borrowing). \`aave.position\` reads the agent's Aave V3 supplied/borrowed/health-factor; \`aave.supply\`/\`aave.withdraw\` move collateral in/out; \`aave.borrow\`/\`aave.repay\` open/close variable-rate debt against that collateral. Borrowing is leverage: the borrow/repay receipts report the resulting health factor (lower = closer to liquidation), and the pre-flight simulation rejects an over-borrow. Surface the health factor when proposing a borrow.
- Token risk: \`risk.token\` vets a token before you hold or buy it — can-you-exit (live quote on Agni/Moe), liquidity depth, restricted-RWA flag, real-contract check — returning a low/elevated/high verdict. Call it before proposing a buy/supply into an unfamiliar token; if it returns high (untradeable / no contract) do NOT trade, and treat restricted/elevated as needing operator confirmation.
- Yield discovery: \`defi.yields\` lists Mantle lending/LP opportunities (via DeFiLlama) ranked by APY or TVL, with risk signals (stablecoin, IL risk, exposure, 7d trend). Use it for "best yield on Mantle" / "where to park USDC". It is ANALYTICS ONLY — it never moves funds; to act on a result, use \`aave.supply\` or \`swap.execute\`. Rows flagged \`restricted: true\` (USDY/MI4/mUSD) need eligibility confirmation before you propose entering them.
- Analysis: \`chain.tx\` decodes any tx hash. \`chain.contract\` introspects code/proxy/ERC standards. \`chain.activity\` shows recent transfers.
- Generic: \`chain.read\`/\`chain.write\` for any contract not covered above; takes \`signature\` + \`args\` like cast.
- Dry-run: \`tx.simulate\` previews ANY call (\`to\` + \`signature\`/\`args\` or raw \`data\`, + optional \`value\`/\`from\`) without broadcasting — returns would-succeed + gas, or the decoded revert reason. Use it to preview an action before \`chain.write\`, debug a revert, or sanity-check a call you're unsure about.
- Blockchain: \`chain.block\` for current head/timestamp/gasUsed. \`chain.gas\` for current gas price.
`
