[[contracts]]
fqn = "nebula_casper_contracts::IdentityRegistry"

[[contracts]]
fqn = "nebula_casper_contracts::ReputationRegistry"

[[contracts]]
fqn = "nebula_casper_contracts::ValidationRegistry"

[[contracts]]
fqn = "nebula_casper_contracts::Amm"
