[[contracts]]
fqn = "nebula_casper_contracts::IdentityRegistry"

[[contracts]]
fqn = "nebula_casper_contracts::ReputationRegistry"

[[contracts]]
fqn = "nebula_casper_contracts::ValidationRegistry"

[[contracts]]
fqn = "nebula_casper_contracts::Amm"

[[contracts]]
fqn = "nebula_casper_contracts::Token"

[[contracts]]
fqn = "nebula_casper_contracts::Treasury"

[[contracts]]
fqn = "nebula_casper_contracts::PayToken"

[[contracts]]
fqn = "nebula_casper_contracts::PayExchange"
