import { randomBytes } from 'node:crypto'
import { describe, expect, test } from 'bun:test'
import { KeyAlgorithm, PrivateKey } from 'casper-js-sdk'
import { encryptToPubkey, generateBootstrapKeypair } from 'nebula-ai-core'
import {
  type ProvisionRequest,
  adminTickHash,
  approvalResponseHash,
  chatMessageHash,
  provisionMessageHash,
  verifyAdminTickSig,
  verifyApprovalSig,
  verifyChatSig,
  verifyProvisionSig,
} from './auth'
import type { RuntimeConfig } from './runtime'

// A CEP-78 identity-token package hash + agent public key fixture.
const INFT_REF = {
  contract: 'hash-9e71d79f06f956d4d2666b5c93dafab721c84721d4d2666b5c93dafab721c8472',
  tokenId: '6',
} as const

const CONFIG: RuntimeConfig = {
  network: 'casper-testnet',
  brain: { provider: 'demo-provider', model: 'glm-5' },
  identity: {
    iNFT: INFT_REF,
    agent: '0203c635e6eb223ae14143e23ceea9440bc773dc87ec223ae14143e23ceea94400b',
  },
}

function hexToBytes(hex: string): Uint8Array {
  const clean = hex.startsWith('0x') ? hex.slice(2) : hex
  const out = new Uint8Array(clean.length / 2)
  for (let i = 0; i < out.length; i++) out[i] = Number.parseInt(clean.slice(i * 2, i * 2 + 2), 16)
  return out
}

function bytesToHex(bytes: Uint8Array): string {
  let s = ''
  for (const b of bytes) s += b.toString(16).padStart(2, '0')
  return s
}

interface Operator {
  privkey: PrivateKey
  publicKeyHex: string
}

/** A fresh Casper secp256k1 operator keypair. */
function newOperator(): Operator {
  const privkey = PrivateKey.fromHex(randomBytes(32).toString('hex'), KeyAlgorithm.SECP256K1)
  return { privkey, publicKeyHex: privkey.publicKey.toHex() }
}

/** Sign a hex digest with the operator's Casper key → algorithm-tagged sig hex. */
async function sign(op: Operator, digestHex: string): Promise<string> {
  const sig = await op.privkey.signAndAddAlgorithmBytes(hexToBytes(digestHex))
  return bytesToHex(sig)
}

function makeRequest(): { req: ProvisionRequest; bootstrapPub: string; agentPriv: string } {
  const bootstrap = generateBootstrapKeypair()
  const agentPriv = `0x${randomBytes(32).toString('hex')}`
  const envelope = encryptToPubkey({
    recipientPubkey: bootstrap.pubkeyHexCompressed,
    plaintext: hexToBytes(agentPriv),
  })
  return {
    req: {
      envelope,
      operatorAddress: '0203000000000000000000000000000000000000000000000000000000000000000000',
      iNFTRef: INFT_REF,
      config: CONFIG,
      ts: Date.now(),
    },
    bootstrapPub: bootstrap.pubkeyHexCompressed,
    agentPriv,
  }
}

describe('provision sig verification', () => {
  test('roundtrip: operator signs the digest, harness verifies', async () => {
    const { req, bootstrapPub } = makeRequest()
    const op = newOperator()
    req.operatorAddress = op.publicKeyHex

    const hash = provisionMessageHash(req, bootstrapPub)
    const sig = await sign(op, hash)

    const r = await verifyProvisionSig({
      request: req,
      signature: sig,
      bootstrapPubkey: bootstrapPub,
      expectedOperator: op.publicKeyHex,
    })
    expect(r.ok).toBe(true)
  })

  test('rejects when operatorAddress does not match expectedOperator', async () => {
    const { req, bootstrapPub } = makeRequest()
    const op = newOperator()
    const wrong = newOperator()
    req.operatorAddress = op.publicKeyHex

    const hash = provisionMessageHash(req, bootstrapPub)
    const sig = await sign(op, hash)

    const r = await verifyProvisionSig({
      request: req,
      signature: sig,
      bootstrapPubkey: bootstrapPub,
      expectedOperator: wrong.publicKeyHex,
    })
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.reason).toBe('operator-mismatch')
  })

  test('rejects when signature was generated by a different key', async () => {
    const { req, bootstrapPub } = makeRequest()
    const op = newOperator()
    const attacker = newOperator()
    req.operatorAddress = op.publicKeyHex

    const hash = provisionMessageHash(req, bootstrapPub)
    const sig = await sign(attacker, hash)

    const r = await verifyProvisionSig({
      request: req,
      signature: sig,
      bootstrapPubkey: bootstrapPub,
      expectedOperator: req.operatorAddress,
    })
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.reason).toBe('sig-mismatch')
  })

  test('rejects sig over a different bootstrap pubkey (replay-against-other-harness)', async () => {
    const { req } = makeRequest()
    const op = newOperator()
    req.operatorAddress = op.publicKeyHex

    const otherGatewayPub = generateBootstrapKeypair().pubkeyHexCompressed
    const realGatewayPub = generateBootstrapKeypair().pubkeyHexCompressed

    const hashForOther = provisionMessageHash(req, otherGatewayPub)
    const sig = await sign(op, hashForOther)

    const r = await verifyProvisionSig({
      request: req,
      signature: sig,
      bootstrapPubkey: realGatewayPub,
      expectedOperator: req.operatorAddress,
    })
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.reason).toBe('sig-mismatch')
  })

  test('rejects sig if config mutated between sign and verify', async () => {
    const { req, bootstrapPub } = makeRequest()
    const op = newOperator()
    req.operatorAddress = op.publicKeyHex
    const hash = provisionMessageHash(req, bootstrapPub)
    const sig = await sign(op, hash)
    // Tamper with config after signing.
    req.config = { ...req.config, brain: { ...req.config.brain, model: 'evil-model' } }
    const r = await verifyProvisionSig({
      request: req,
      signature: sig,
      bootstrapPubkey: bootstrapPub,
      expectedOperator: req.operatorAddress,
    })
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.reason).toBe('sig-mismatch')
  })

  test('rejects stale ts', async () => {
    const { req, bootstrapPub } = makeRequest()
    const op = newOperator()
    req.operatorAddress = op.publicKeyHex
    const now = 1_000_000_000_000
    req.ts = now - 10 * 60 * 1000

    const hash = provisionMessageHash(req, bootstrapPub)
    const sig = await sign(op, hash)

    const r = await verifyProvisionSig({
      request: req,
      signature: sig,
      bootstrapPubkey: bootstrapPub,
      expectedOperator: req.operatorAddress,
      now,
    })
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.reason).toBe('ts-stale')
  })

  test('rejects ts too far in the future', async () => {
    const { req, bootstrapPub } = makeRequest()
    const op = newOperator()
    req.operatorAddress = op.publicKeyHex
    const now = 1_000_000_000_000
    req.ts = now + 5 * 60 * 1000

    const hash = provisionMessageHash(req, bootstrapPub)
    const sig = await sign(op, hash)

    const r = await verifyProvisionSig({
      request: req,
      signature: sig,
      bootstrapPubkey: bootstrapPub,
      expectedOperator: req.operatorAddress,
      now,
    })
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.reason).toBe('ts-future')
  })

  test('survives JSON.stringify→parse roundtrip when config carries undefined-valued optional fields', async () => {
    // Regression: the CLI builds RuntimeConfig with `promptAppend: undefined`
    // (caller didn't set it). It signs the in-memory config, JSON.stringify
    // drops the field on the wire, and the harness's parsed config has no
    // `promptAppend` key. If `stableStringify` hashed `undefined` as the
    // literal text "undefined" for the CLI but skipped the key for the harness,
    // hashes differed.
    const { req, bootstrapPub } = makeRequest()
    const op = newOperator()
    req.operatorAddress = op.publicKeyHex
    req.config = {
      ...req.config,
      // biome-ignore lint/suspicious/noExplicitAny: deliberately exercising the optional-undefined path
      promptAppend: undefined as any,
      // biome-ignore lint/suspicious/noExplicitAny: same
      plugins: undefined as any,
    }
    const hashCli = provisionMessageHash(req, bootstrapPub)
    const sig = await sign(op, hashCli)

    // Simulate the wire roundtrip the harness sees.
    const reqOnWire = JSON.parse(JSON.stringify(req)) as ProvisionRequest
    expect((reqOnWire.config as unknown as Record<string, unknown>).promptAppend).toBeUndefined()
    expect(Object.hasOwn(reqOnWire.config, 'promptAppend')).toBe(false)

    const r = await verifyProvisionSig({
      request: reqOnWire,
      signature: sig,
      bootstrapPubkey: bootstrapPub,
      expectedOperator: req.operatorAddress,
    })
    expect(r.ok).toBe(true)
  })
})

describe('chat sig verification', () => {
  test('roundtrip', async () => {
    const op = newOperator()
    const ts = Date.now()
    const hash = chatMessageHash('hello', ts, 'sbx-1')
    const sig = await sign(op, hash)
    const r = await verifyChatSig({
      message: 'hello',
      ts,
      sandboxId: 'sbx-1',
      signature: sig,
      expectedOperator: op.publicKeyHex,
    })
    expect(r.ok).toBe(true)
  })

  test('rejects signature from a different sandbox', async () => {
    const op = newOperator()
    const ts = Date.now()
    const sigForOther = await sign(op, chatMessageHash('hello', ts, 'sbx-other'))
    const r = await verifyChatSig({
      message: 'hello',
      ts,
      sandboxId: 'sbx-real',
      signature: sigForOther,
      expectedOperator: op.publicKeyHex,
    })
    expect(r.ok).toBe(false)
  })
})

describe('admin tick sig verification', () => {
  test('roundtrip for autotopup-tick action', async () => {
    const op = newOperator()
    const ts = Date.now()
    const hash = adminTickHash({ action: 'autotopup-tick', ts, sandboxId: 'sbx-enigma' })
    const sig = await sign(op, hash)
    const r = await verifyAdminTickSig({
      action: 'autotopup-tick',
      ts,
      sandboxId: 'sbx-enigma',
      signature: sig,
      expectedOperator: op.publicKeyHex,
    })
    expect(r.ok).toBe(true)
  })

  test('rejects sig for a different action (cross-action replay)', async () => {
    const op = newOperator()
    const ts = Date.now()
    const sigForOther = await sign(op, adminTickHash({ action: 'sync-trigger', ts, sandboxId: 'sbx-1' }))
    const r = await verifyAdminTickSig({
      action: 'autotopup-tick',
      ts,
      sandboxId: 'sbx-1',
      signature: sigForOther,
      expectedOperator: op.publicKeyHex,
    })
    expect(r.ok).toBe(false)
    if (r.ok) throw new Error('unreachable')
    expect(r.reason).toBe('sig-mismatch')
  })

  test('rejects sig for a different sandbox', async () => {
    const op = newOperator()
    const ts = Date.now()
    const sigForOther = await sign(op, adminTickHash({ action: 'autotopup-tick', ts, sandboxId: 'sbx-other' }))
    const r = await verifyAdminTickSig({
      action: 'autotopup-tick',
      ts,
      sandboxId: 'sbx-real',
      signature: sigForOther,
      expectedOperator: op.publicKeyHex,
    })
    expect(r.ok).toBe(false)
  })

  test('rejects expired ts (>5 min stale)', async () => {
    const op = newOperator()
    const ts = Date.now() - 6 * 60 * 1000
    const hash = adminTickHash({ action: 'autotopup-tick', ts, sandboxId: 'sbx-1' })
    const sig = await sign(op, hash)
    const r = await verifyAdminTickSig({
      action: 'autotopup-tick',
      ts,
      sandboxId: 'sbx-1',
      signature: sig,
      expectedOperator: op.publicKeyHex,
    })
    expect(r.ok).toBe(false)
    if (r.ok) throw new Error('unreachable')
    expect(r.reason).toBe('ts-stale')
  })

  test('rejects future-skewed ts (>1 min ahead)', async () => {
    const op = newOperator()
    const ts = Date.now() + 2 * 60 * 1000
    const hash = adminTickHash({ action: 'autotopup-tick', ts, sandboxId: 'sbx-1' })
    const sig = await sign(op, hash)
    const r = await verifyAdminTickSig({
      action: 'autotopup-tick',
      ts,
      sandboxId: 'sbx-1',
      signature: sig,
      expectedOperator: op.publicKeyHex,
    })
    expect(r.ok).toBe(false)
    if (r.ok) throw new Error('unreachable')
    expect(r.reason).toBe('ts-future')
  })
})

describe('approval sig verification', () => {
  test('roundtrip', async () => {
    const op = newOperator()
    const ts = Date.now()
    const hash = approvalResponseHash({
      approvalId: 'apv-1',
      decision: 'allow',
      ts,
      sandboxId: 'sbx-1',
    })
    const sig = await sign(op, hash)
    const r = await verifyApprovalSig({
      approvalId: 'apv-1',
      decision: 'allow',
      ts,
      sandboxId: 'sbx-1',
      signature: sig,
      expectedOperator: op.publicKeyHex,
    })
    expect(r.ok).toBe(true)
  })

  test('rejects mismatched decision', async () => {
    const op = newOperator()
    const ts = Date.now()
    const sig = await sign(
      op,
      approvalResponseHash({ approvalId: 'apv-1', decision: 'allow', ts, sandboxId: 'sbx-1' }),
    )
    const r = await verifyApprovalSig({
      approvalId: 'apv-1',
      decision: 'deny',
      ts,
      sandboxId: 'sbx-1',
      signature: sig,
      expectedOperator: op.publicKeyHex,
    })
    expect(r.ok).toBe(false)
  })
})
